server:
  port: 8080

spring:
  # mysql
  datasource:
    url: jdbc:mysql://localhost:3306/ebook?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 12345678
#    password: root
  data:
    # redis
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 100ms
      database: 0