server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ebook?useSSL=false&serverTimezone=shanghai
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 100ms
      database: 0